# Generated by Django 3.1.7 on 2021-04-04 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('payment_intent_stripe_id', models.CharField(max_length=255)),
                ('customer_stripe_id', models.CharField(max_length=255)),
                ('product_stripe_id', models.CharField(max_length=255)),
                ('price_stripe_id', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('amount_total', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('course', 'membership')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
