# Generated by Django 3.1.7 on 2021-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210406_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
