# Generated by Django 3.1.8 on 2021-05-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Ordine', 'verbose_name_plural': 'Ordini'},
        ),
    ]
