# Generated by Django 3.1.7 on 2021-04-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0002_caregiverpro_caregiverpromore_category_company_employee_employeemore_familymember_jobpost_person_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverpromore',
            name='house_number',
            field=models.CharField(default=None, max_length=10, verbose_name='Civico'),
        ),
        migrations.AddField(
            model_name='personmore',
            name='house_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Civico'),
        ),
    ]
