# Generated by Django 3.1.7 on 2021-04-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0003_auto_20210403_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverpromore',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('FEMALE', 'Femmina'), ('MALE', 'maschio')], default='', max_length=25, verbose_name='Sesso'),
        ),
        migrations.AlterField(
            model_name='caregiverpromore',
            name='how_know_us',
            field=models.CharField(blank=True, choices=[(None, ''), ('GOOGLE', 'Google'), ('YOUTUBE', 'Youtube'), ('FORUM', 'Gruppi o Forum'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'Linkedin'), ('BANNER', 'Banner Ads'), ('FRIENDS', 'Amici e Famiglia'), ('PRESS', 'Press: News, Magazine, Blog'), ('OTHER', 'Altro')], max_length=35),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('FEMALE', 'Femmina'), ('MALE', 'maschio')], default='', max_length=25, verbose_name='Sesso'),
        ),
        migrations.AlterField(
            model_name='personmore',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('FEMALE', 'Femmina'), ('MALE', 'maschio')], default='', max_length=25, verbose_name='Sesso'),
        ),
        migrations.AlterField(
            model_name='personmore',
            name='how_know_us',
            field=models.CharField(blank=True, choices=[(None, ''), ('GOOGLE', 'Google'), ('YOUTUBE', 'Youtube'), ('FORUM', 'Gruppi o Forum'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'Linkedin'), ('BANNER', 'Banner Ads'), ('FRIENDS', 'Amici e Famiglia'), ('PRESS', 'Press: News, Magazine, Blog'), ('OTHER', 'Altro')], max_length=35),
        ),
    ]
