# Generated by Django 3.1.8 on 2021-04-17 15:11

from django.db import migrations, models
import lianecare.solace.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0004_auto_20210411_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverpromore',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('FEMALE', 'Femmina'), ('MALE', 'Maschio')], default='', max_length=25, verbose_name='Sesso'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='diagnosis',
            field=lianecare.solace.fields.ChoiceArrayField(base_field=models.CharField(choices=[(None, ''), ('ADD', 'Add'), ('ADHD', "Disturbo da deficit dell'attenzione e iperattività (ADHD)"), ('ASPERGERS', 'Aspergers'), ('ASTHMA', 'Asma'), ('AUTISM', 'Autismo'), ('BLINDNESS', 'Cecità / Deficit visivo'), ('CANCER', 'Cancro'), ('CELIAC', 'Celiachia'), ('CEREBRAL_PALSY', 'Paralisi cerebrale'), ('CYSTIC_FIBROSIS', 'Fibrosi cistica'), ('DEAFNESS', 'Sordità'), ('DEVELOPMENT_DELAYS', 'Ritardo nello sviluppo'), ('DIABETES', 'Diabete'), ('DOWN', 'Sindrome di Down'), ('DWARFISM', 'Nanismo'), ('DYSLEXIA', 'Dislessia'), ('EPILEPSY', 'Epilessia'), ('FETAL_SYNDROME', 'Sindrome alcolica fetale'), ('FOOD_ALLERGIES', 'Allergie alimentari'), ('HEART_DEFECTS', 'Disturbi cardiaci'), ('MENTAL_ILLNESS', 'Malattia mentale'), ('MOBILITY_CHALLENGES', 'Disturbi motori'), ('SCLEROSIS', 'Sclerosi Multipla'), ('MUSCOLAR_DYSTROPHY', 'Distrofia muscolare'), ('OBESITY', 'Obesità'), ('SEIZURE', 'Crisi convulsive'), ('SENSORY_DISORDER', 'Disturbi sensoriali'), ('SPEECH_DELAY', 'Ritardo nel parlato')], max_length=25, verbose_name='Patologie'), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('FEMALE', 'Femmina'), ('MALE', 'Maschio')], default='', max_length=25, verbose_name='Sesso'),
        ),
        migrations.AlterField(
            model_name='personmore',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('FEMALE', 'Femmina'), ('MALE', 'Maschio')], default='', max_length=25, verbose_name='Sesso'),
        ),
    ]
