# Generated by Django 3.1.8 on 2021-04-18 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0005_auto_20210417_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='solace.caregiverpro'),
        ),
    ]
