# Generated by Django 3.1.8 on 2021-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0007_auto_20210418_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmore',
            name='has_basic_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmore',
            name='has_pro_course',
            field=models.BooleanField(default=False),
        ),
    ]
