# Generated by Django 3.1.8 on 2021-05-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0008_auto_20210418_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='caregiverpromore',
            name='skills',
        ),
    ]
