# Generated by Django 3.1.8 on 2021-05-02 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solace', '0010_auto_20210502_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='person',
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
