# Generated by Django 3.1.8 on 2021-05-02 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solace', '0012_auto_20210502_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Indirizzo'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Città'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=65, null=True, verbose_name='Nazione'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Anni di esperienza'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='has_references',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Referenze?'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='house_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Civico'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Attivo?'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note aggiuntive'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='postcode',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=65, null=True, verbose_name='Regione'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='jobpost',
            unique_together={('user', 'category')},
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='person',
        ),
    ]
