# Generated by Django 3.1.8 on 2021-05-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0013_auto_20210502_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='start_date',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='when',
            field=models.IntegerField(choices=[(None, ''), ('GOOGLE', 'Google'), ('YOUTUBE', 'Youtube'), ('FORUM', 'Gruppi o Forum'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'Linkedin'), ('BANNER', 'Banner Ads'), ('FRIENDS', 'Amici e Famiglia'), ('PRESS', 'Press: News, Magazine, Blog'), ('OTHER', 'Altro')], default=0),
        ),
    ]
