# Generated by Django 3.1.8 on 2021-05-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0014_auto_20210504_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='experience',
            field=models.IntegerField(choices=[(None, 'Seleziona'), (0, 'Indifferente'), (3, '+3 anni'), (5, '+5 anni'), (10, '+10 anni')], default=0, verbose_name='Anni di esperienza'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='when',
            field=models.IntegerField(choices=[(None, 'Seleziona'), (0, 'Indifferente'), (1, 'Il prima possibile'), (7, 'Entro una settimana'), (30, 'Entro un mese')], default=0),
        ),
    ]
