# Generated by Django 3.1.8 on 2021-05-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0016_auto_20210504_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[(None, ''), ('NO_SHOW', 'Non visibile'), ('ACTIVE', 'Pubblicato'), ('KO_DONT_NEED', 'Non ne ho più bisogno'), ('KO_OTHER_PLATFORM', 'Ho trovato il Caregiver con altre piattaforme'), ('KO_OTHER', 'Ho trovato il Caregiver in altro modo'), ('OK_SOLACE', 'Ho trovato il Caregiver con LianeCare')], default='ACTIVE', max_length=55),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='has_references',
            field=models.BooleanField(default=False, verbose_name='Referenze?'),
        ),
    ]
