# Generated by Django 3.1.8 on 2021-05-06 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0018_auto_20210506_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='when',
            field=models.IntegerField(choices=[(None, 'Seleziona'), (0, 'Indifferente'), (7, 'Entro 7 gg'), (14, 'Entro 14 gg'), (30, 'Entro 30 gg')]),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_caregiverpro', models.IntegerField(choices=[(0, 'Proposto'), (1, 'Ignorato'), (2, 'Chat'), (3, 'Rifiutato'), (4, 'Approvato'), (5, 'Recensito')], default=0)),
                ('status_employee', models.IntegerField(choices=[(0, 'Proposto'), (1, 'Ignorato'), (2, 'Chat'), (3, 'Rifiutato'), (4, 'Approvato'), (5, 'Recensito')], default=0)),
                ('caregiverpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solace.caregiverpro')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solace.jobpost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='candidates',
            field=models.ManyToManyField(through='solace.Proposal', to='solace.CaregiverPro'),
        ),
    ]
