# Generated by Django 3.1.8 on 2021-05-06 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0019_auto_20210506_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
