# Generated by Django 3.1.8 on 2021-05-06 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0020_proposal_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
