# Generated by Django 3.1.8 on 2021-05-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0022_proposal_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ('-created',), 'verbose_name': 'Proposta', 'verbose_name_plural': 'Proposte'},
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='when',
            field=models.IntegerField(choices=[(None, 'Seleziona'), (0, 'indifferente'), (7, 'entro 7 gg'), (14, 'entro 14 gg'), (30, 'entro 30 gg')]),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status_caregiverpro',
            field=models.IntegerField(choices=[(-2, 'Rifiutato'), (-1, 'Ignorato'), (0, 'Proposto'), (1, 'Chat'), (2, 'Approvato'), (3, 'Recensito')], default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status_employee',
            field=models.IntegerField(choices=[(-2, 'Rifiutato'), (-1, 'Ignorato'), (0, 'Proposto'), (1, 'Chat'), (2, 'Approvato'), (3, 'Recensito')], default=0),
        ),
    ]
