# Generated by Django 3.1.8 on 2021-05-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0023_auto_20210507_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status_caregiverpro',
            field=models.IntegerField(choices=[(-4, 'Eliminato'), (-3, 'Scaduto'), (-2, 'Rifiutato'), (-1, 'Ignorato'), (0, 'Proposto'), (1, 'Chat'), (2, 'Approvato'), (3, 'Recensito')], default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status_employee',
            field=models.IntegerField(choices=[(-4, 'Eliminato'), (-3, 'Scaduto'), (-2, 'Rifiutato'), (-1, 'Ignorato'), (0, 'Proposto'), (1, 'Chat'), (2, 'Approvato'), (3, 'Recensito')], default=0),
        ),
    ]
