# Generated by Django 3.1.8 on 2021-05-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0025_auto_20210508_0545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobpost',
            unique_together=set(),
        ),
    ]
