# Generated by Django 3.1.8 on 2021-06-09 06:00

from django.db import migrations, models
import django.db.models.deletion
import lianecare.solace.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0026_auto_20210509_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='diagnosis',
            field=lianecare.solace.fields.ChoiceArrayField(base_field=models.CharField(choices=[(None, ''), ('OTHER', 'Altro'), ('FOOD_ALLERGIES', 'Allergie alimentari'), ('ASTHMA', 'Asma'), ('ASPERGERS', 'Aspergers'), ('AUTISM', 'Autismo'), ('CANCER', 'Cancro'), ('BLINDNESS', 'Cecità / Deficit visivo'), ('CELIAC', 'Celiachia'), ('SEIZURE', 'Crisi convulsive'), ('DIABETES', 'Diabete'), ('DYSLEXIA', 'Dislessia'), ('MUSCOLAR_DYSTROPHY', 'Distrofia muscolare'), ('HEART_DEFECTS', 'Disturbi cardiaci'), ('MOBILITY_CHALLENGES', 'Disturbi motori'), ('SENSORY_DISORDER', 'Disturbi sensoriali'), ('ADHD', "Disturbo da deficit dell'attenzione e iperattività (ADHD)"), ('EPILEPSY', 'Epilessia'), ('CYSTIC_FIBROSIS', 'Fibrosi cistica'), ('MENTAL_ILLNESS', 'Malattia mentale'), ('DWARFISM', 'Nanismo'), ('OBESITY', 'Obesità'), ('CEREBRAL_PALSY', 'Paralisi cerebrale'), ('DEVELOPMENT_DELAYS', 'Ritardo nello sviluppo'), ('SPEECH_DELAY', 'Ritardo nel parlato'), ('SCLEROSIS', 'Sclerosi Multipla'), ('FETAL_SYNDROME', 'Sindrome alcolica fetale'), ('DOWN', 'Sindrome di Down'), ('DEAFNESS', 'Sordità')], max_length=25, verbose_name='Patologie'), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='subcategories',
            field=models.ManyToManyField(to='solace.SubCategory'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='solace.person'),
        ),
    ]
