# Generated by Django 3.1.8 on 2021-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0027_auto_20210609_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverpromore',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregiverpromore',
            name='notify_new_jobpost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caregiverpromore',
            name='notify_new_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personmore',
            name='notify_new_jobpost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personmore',
            name='notify_new_message',
            field=models.BooleanField(default=True),
        ),
    ]
