# Generated by Django 3.1.8 on 2021-06-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0030_auto_20210627_1816'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('jobpost', 'caregiverpro'), name='unique_caregiver'),
        ),
    ]
