# Generated by Django 3.1.8 on 2021-06-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0031_auto_20210627_1821'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proposal',
            name='unique_caregiver',
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('caregiverpro', 'jobpost'), name='unique_caregiver'),
        ),
    ]
