# Generated by Django 3.1.8 on 2021-06-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0033_auto_20210627_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'code'), name='unique_subcategory_category'),
        ),
    ]
