# Generated by Django 3.1.13 on 2022-03-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0034_auto_20210627_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ('-created',), 'verbose_name': 'Job Post', 'verbose_name_plural': 'Job Posts'},
        ),
    ]
