# Generated by Django 3.1.8 on 2021-05-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_auto_20210417_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Risposta', 'verbose_name_plural': 'Risposte'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Domanda', 'verbose_name_plural': 'Domande'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Esito test', 'verbose_name_plural': 'Esiti test'},
        ),
    ]
