# Generated by Django 3.1.8 on 2021-05-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_auto_20210502_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
    ]
