# Generated by Django 3.1.8 on 2021-05-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_remove_quiz_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='numbers_of_questions',
            field=models.IntegerField(verbose_name='Numero domande'),
        ),
        migrations.AlterField(
            model_name='result',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Superato?'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.FloatField(verbose_name='Punteggio'),
        ),
    ]
