# Generated by Django 3.1.13 on 2023-01-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0007_auto_20230113_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(to='quizes.Quiz'),
        ),
    ]
