# Generated by Django 3.1.5 on 2021-02-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210218_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='Durata in minuti'),
        ),
    ]
