# Generated by Django 3.1.5 on 2021-02-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_module_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='Durata in minuti'),
        ),
    ]
