# Generated by Django 3.1.7 on 2021-03-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210301_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Attivo'),
        ),
    ]
