# Generated by Django 3.1.7 on 2021-03-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_module_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
