# Generated by Django 3.1.7 on 2021-03-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210324_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='id_product_stipe',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID Prodotto in Stripe'),
        ),
    ]
