# Generated by Django 3.1.7 on 2021-03-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
        ('courses', '0011_auto_20210328_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='product_stripe',
            field=models.OneToOneField(blank=True, help_text='The Stripe product id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.product'),
        ),
    ]
