# Generated by Django 3.1.7 on 2021-03-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_product_stripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_salable',
            field=models.BooleanField(default=True, verbose_name='In vendita'),
        ),
    ]
