# Generated by Django 3.1.7 on 2021-03-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210328_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id_product_stipe',
        ),
    ]
