# Generated by Django 3.1.7 on 2021-03-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20210329_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='duration',
        ),
        migrations.AddField(
            model_name='module',
            name='minutes',
            field=models.PositiveIntegerField(default=1, verbose_name='Durata: minuti'),
        ),
        migrations.AddField(
            model_name='module',
            name='seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Durata: secondi'),
        ),
    ]
