# Generated by Django 3.1.7 on 2021-04-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
        ('courses', '0018_auto_20210403_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='product_stripe',
            new_name='product_id_stripe',
        ),
        migrations.AddField(
            model_name='course',
            name='price_id_stripe',
            field=models.OneToOneField(blank=True, help_text='ID prezzo in Stripe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.price'),
        ),
    ]
