# Generated by Django 3.1.7 on 2021-04-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20210403_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='price_id_stripe',
            new_name='price_stripe',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='product_id_stripe',
            new_name='product_stripe',
        ),
    ]
