# Generated by Django 3.1.7 on 2021-04-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_product_description'),
        ('courses', '0020_auto_20210403_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='charge_stripe',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='order',
            field=models.OneToOneField(blank=True, help_text='ID ordine', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
