# Generated by Django 3.1.7 on 2021-04-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_enrollment_session_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
    ]
