# Generated by Django 3.1.7 on 2021-04-07 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_module_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='viewed',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Da iniziare'), (1, 'In corso'), (2, 'Completato'), (3, 'Superato')], default=0, verbose_name='Stato'),
        ),
        migrations.CreateModel(
            name='EnrollmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('viewed', models.BooleanField(default=False, verbose_name='Visto')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.enrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='modules',
            field=models.ManyToManyField(through='courses.EnrollmentStatus', to='courses.Module'),
        ),
    ]
