# Generated by Django 3.1.7 on 2021-04-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20210407_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentstatus',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
