# Generated by Django 3.1.7 on 2021-04-08 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_order_product_description'),
        ('courses', '0026_auto_20210407_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='ID ordine', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
    ]
