# Generated by Django 3.1.7 on 2021-04-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_product_description'),
        ('courses', '0027_auto_20210408_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='order',
            field=models.ForeignKey(blank=True, default=None, help_text='ID ordine', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
