# Generated by Django 3.1.7 on 2021-04-08 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20210408_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentstatus',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
