# Generated by Django 3.1.7 on 2021-04-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_enrollmentstatus_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentstatus',
            options={'ordering': ['order', 'viewed']},
        ),
    ]
