# Generated by Django 3.1.8 on 2021-04-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_course_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentstatus',
            options={'ordering': ['order']},
        ),
    ]
