# Generated by Django 3.1.8 on 2021-05-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20210506_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
