# Generated by Django 3.1.8 on 2021-05-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created']},
        ),
    ]
