# Generated by Django 3.1.13 on 2022-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20210509_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user_type',
            field=models.CharField(choices=[('PERSON', 'Persona'), ('EMPLOYEE', 'Dipendente'), ('PRO', 'Caregiver PRO'), ('STAFF', 'STAFF')], default='PERSON', max_length=50, verbose_name='Tipo'),
        ),
    ]
