# Generated by Django 3.1.13 on 2022-12-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_course_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['sequence', '-created'], 'verbose_name': 'Corso', 'verbose_name_plural': 'Corsi'},
        ),
        migrations.AddField(
            model_name='course',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='Sequenza'),
        ),
    ]
