# Generated by Django 3.1.13 on 2023-02-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20221231_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_offer',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Tipo'),
        ),
    ]
