# Generated by Django 3.1.13 on 2023-02-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20230213_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_offer',
            field=models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='offerta del corso'),
        ),
    ]
