#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


>&2 echo 'Starting... collectstatic'

python /app/manage.py collectstatic --noinput
#
#compress_enabled() {
#python << END
#import sys
#
#from environ import Env
#
#env = Env(COMPRESS_ENABLED=(bool, True))
#if env('COMPRESS_ENABLED'):
#    sys.exit(0)
#else:
#    sys.exit(1)
#
#END
#}
#
#if compress_enabled; then
#  # NOTE this command will fail if django-compressor is disabled
#
#  >&2 echo 'Starting... compress'
#  python /app/manage.py compress
#fi
