# Generated by Django 3.1.7 on 2021-03-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('PERSON', 'Persona'), ('EMPLOYEE', 'Dipendente'), ('PRO', 'Caregiver PRO')], default='PERSON', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
